# Database configuration
database:
  # The type of database you're using (e.g., SQLite, MySQL, etc.)
  type: SQLite

  # The host for the database (e.g., localhost or IP address)
  host: localhost:3306

  # Name of the database to connect to
  database: beacmcAuth

  # Database username for authentication
  username: beacmc

  # Password for the database user (ensure it’s stored securely)
  password: "MyVeryVeryVeryHardPassword228"

  # Whether the server should stop if the connection to the database fails
  stop-server-on-failed-connection: true

# Session timeout in minutes (e.g., after 10 minutes, users will be logged out)
session-time: 10

# List of disabled servers, where authentication will not be required
disabled-servers:
  - grief-1
  - grief-2
  - anarchy-1

# Regular expression for nickname validation (letters, numbers, and underscores allowed)
nickname-regex: '[a-zA-Z0-9_]*'

# Time (in seconds) required between each login attempt
time-per-login: 60

# Time (in seconds) required between each registration attempt
time-per-register: 60

# Control whether the case of the player's name should match exactly as registered
name-case-control: false

# Debug mode
debug: false

# Maximum number of incorrect password attempts before locking the user
password-attempts: 3

# Minimum and maximum password length requirements
password-min-length: 6
password-max-length: 30

# Number of bcrypt rounds for password hashing (increase for more security)
bcrypt-rounds: 10

# Command to link accounts (for Discord, Telegram, etc.)
link-command: "link"

# Authentication and game servers configuration with their max online player limits
# Format: <server-name>:<max-online-players>
auth-servers:
  - auth:100

game-servers:
  - lobby:100

# Whitelist commands that should always be allowed without authentication
whitelist-commands:
  - '/l'        # Short alias for login command
  - '/log'      # Another alias for login command
  - '/login'    # Main login command
  - '/reg'      # Short alias for registration command
  - '/register' # Main registration command

# Messages for various events and actions

messages:
  # Registration messages
  register-chat: "&7Register: &#ffbb00/reg &7(&#ffbb00&lpassword&r&7) &7(&#ffbb00&lpassword&r&7)"
  register-title: "&7"
  register-subtitle: "&7Register an account"
  passwords-dont-match: "&7The passwords don't match"
  low-character-password: "&7There are not enough characters in the password"
  high-character-password: "&7There are too many characters in the password"
  not-register: "&7You're not registered"
  register-success: "&7Registration successful"
  confirm-password: "&7Repeat your password in the second argument"

  # Login messages
  already-register: "&7You are already registered"
  login-chat: "&7Login: &#ffbb00/login &7(&#ffbb00&lpassword&r&7)"
  login-title: "&7"
  login-subtitle: "&7Login to your account"
  wrong-password: "&7The password is wrong. Attempts left: %attempts%"
  attempts-left: "&cAttempts to enter the password have been exhausted"
  login-success: "&7Authorization successful"

  # Change password messages
  change-password-command-usage: "&7Usage: /cp <old-password> <new-password>"
  old-password-wrong: "&7The old password is incorrect"
  change-password-success: "&7You have successfully changed your old password to a new one"
  passwords-match: "&7Your old password and your new password are identical"

  # Admin commands
  auth-reload: "&7Configuration rebooted"
  account-not-found: "&7Account not found"
  account-deleted: "&7Account successfully deleted"
  account-not-register: "&7Account not yet registered"
  your-account-deleted-disconnect: "&cYour account has been deleted"
  account-password-changed: "&7Account password successfully changed"
  auth-help: |-
    #ffbb00&lBeacmcAuth commands
    #ffbb00&m       &r
    &7auth  
    &7 - #ffbb00reload &8:&7 reload config
    &7 - #ffbb00delete <account> &8:&7 delete account
    &7 - #ffbb00changepass <account> <pass> &8:&7 change account password

  # General authentication messages
  already-authed: "&7You are already logged in"
  enter-password: "&7You have not entered your password"
  session-active: "&7Server recognized you, authorization is not required"
  invalid-character-in-name: "&7Invalid characters are detected in the name"
  find-server-error: "&cAll servers are full or there is no communication with them. Please wait..."
  time-is-up: "&cAuthorization time is up, try again"
  blocked-server: "&cAuthorize to connect to this server"
  internal-error: |-
    &c&lWARNING!!!
    &fThere was an internal error. Please contact the administration.

  # Name case mismatch message
  name-case-failed: |-
    &7Your nickname does not match the nickname you registered under. 
    &fCurrent name: &#ffbb00%current_name%
    &7Required name: &#ffbb00%need_name%

  # Discord-related messages
  discord-private-messages-closed: "&cYour private messages are closed. It is not possible to enter the game"
  discord-confirmation-chat: "&7Confirm account login in your discord's private messages"
  discord-confirmation-title: "&7"
  discord-confirmation-subtitle: "&7Confirm the discord login"
  discord-confirmation-denied: "&cEntry denied in discord's private messages"
  discord-confirmation-success: "&7Login confirmed, you will be redirected to the server"
  discord-kick: "&cYou were kicked at the discord request"

  # Telegram-related messages
  telegram-private-messages-closed: "&cYour private messages are closed. It is not possible to enter the game"
  telegram-confirmation-chat: "&7Confirm account login in your Telegram private messages"
  telegram-confirmation-title: "&7"
  telegram-confirmation-subtitle: "&7Confirm the Telegram login"
  telegram-confirmation-denied: "&cEntry denied in Telegram private messages"
  telegram-confirmation-success: "&7Login confirmed, you will be redirected to the server"
  telegram-kick: "&cYou were kicked at the Telegram request"

  # Account linking messages
  link-code-absent: "&7No code has been sent to your account yet"
  link-command-usage: "&7Usage: &#ffbb00/link <code>"
  incorrect-code: "&7You have entered the wrong code for the binding"
  link-success: "&7You have successfully linked your account"
  
  # Account blocked message
  account-banned: "&cAccount blocked via a social network"